// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yb_Z81NK6eBCvA0f0Wi2kMETanjekpY',
    appId: '1:907409704767:web:fe8c84196a68e6cdbff58a',
    messagingSenderId: '907409704767',
    projectId: 'crypto-coin-5b285',
    authDomain: 'crypto-coin-5b285.firebaseapp.com',
    storageBucket: 'crypto-coin-5b285.appspot.com',
    measurementId: 'G-4KR76TTCME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNGuyYJqMOcoGPeSPMqP0zQXZ7fAcWTc',
    appId: '1:907409704767:android:acb73ac156fbf94dbff58a',
    messagingSenderId: '907409704767',
    projectId: 'crypto-coin-5b285',
    storageBucket: 'crypto-coin-5b285.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1yb_Z81NK6eBCvA0f0Wi2kMETanjekpY',
    appId: '1:907409704767:web:4b2e707700320f6cbff58a',
    messagingSenderId: '907409704767',
    projectId: 'crypto-coin-5b285',
    authDomain: 'crypto-coin-5b285.firebaseapp.com',
    storageBucket: 'crypto-coin-5b285.appspot.com',
    measurementId: 'G-608EL1XBRV',
  );
}
